name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Copy built files to root
      if: github.ref == 'refs/heads/main'
      run: |
        # Remove existing built files from root (but keep source files)
        rm -f index.html
        rm -rf assets
        # Copy built files from dist to root
        cp -r dist/* .
        # Clean up dist folder
        rm -rf dist
        
    - name: Commit and push built files
      if: github.ref == 'refs/heads/main'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.html assets vite.svg
        git diff --staged --quiet || git commit -m "Deploy built files to root for GitHub Pages"
        git push